<!-- Modal -->
<div class="modal fade" id="id-modal-alerta" tabindex="-1" aria-labelledby="modal-alerta-titulo" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="modal-alerta-titulo"><?php if (isset($this->view->titulo)) echo $this->view->titulo; ?></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modal-alerta-conteudo">
        <?php if (isset($this->view->texto)) echo $this->view->texto; ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>