<div class="form-group">
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="row">
                <div class="col-12">
                    <label for="categoria">Nome Categoria</label>
                    <input type="text" class="form-control" id="categoria" name="categoria" required>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-6 col-12">
                        <label for="tipo">Tipo</label>
                        <input type="text" class="form-control" id="tipo" placeholder="(R, D, A ou RA)" name="tipo" required>
                    </div>
                    <div class="col-sm-6 col-12">
                        <label for="tipo">Sinal</label>
                        <input type="text" class="form-control" id="sinal" placeholder="(+ ou -)" name="sinal" required>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <small class="text-muted">
                <strong>Tipo +</strong> para entradas (Receitas ou Resgates)<br>
                <strong>Tipo -</strong> para saídas (Despesas ou Aplicações)<br>
                <strong>R</strong> para Receita<br>
                <strong>D</strong> para Despesa<br>
                <strong>A</strong> para Aplicação<br>
                <strong>RA</strong> para Resgate de Aplicação
            </small>
        </div>
    </div>
</div>