<div class="container">

    <div class="mt-2 mb-2">
		<div class="card p-2">
			<div class="text-center">Extrato dos Investimentos</div>
		</div>
	</div>

    <div class="card mt-2">
        <div class="card-header bg-dark text-white">
            <h6 class="card-title mb-0">Filtro</h6>
        </div>
        <div class="card-body p-1">
            <form method="POST" data-action="<?= $action; ?>" class="submit-form-render-ajax" data-div="<?= $div; ?>">
                <div class="form-group m-2">
                    <div class="row">
                        <div class="col-2">
                            <label for="idExtratoAno">Ano</label>
                            <select class="form-select" id="idExtratoAno" name="extratoAno">
                                <?php foreach ($years as $v): ?>
                                    <option value="<?= $v; ?>" <?= $v == date('Y') ? ' selected ' : ''; ?>><?= $v; ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <div class="col-2">
                            <label for="idExtratoMes">Mês</label>
                            <select class="form-select" id="idExtratoMes" name="extratoMes">
                                <option value="">Trimestre</option>
                                <?php foreach ($months as $v): ?>
                                    <option value="<?= $v; ?>"><?= $v; ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <div class="col-3">
                            <label for="idExtratoInvest">Invest</label>
                            <select class="form-select" id="idExtratoInvest" name="extratoInvest">
                                <option value="">Todos</option>
                                <?php foreach ($lista_invest as $v): ?>
                                    <option value="<?= $v['idContaInvest']; ?>"><?= $v['nomeBanco'] . ' - ' . $v['tituloInvest']; ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <div class="col-3">
                            <label for="idAcaoInvest">Ação</label>
                            <select class="form-select" id="idAcaoInvest" name="acaoInvest">
                                <option value="">Todos</option>
                                <?php 
                                    foreach ($lista_acao as $v): 
                                        $acao = match ($v['tipo']) {
                                            '1' => 'Prejuízo',
                                            '2' => 'Lucro',
                                            '3' => 'Resgate',
                                            '4' => 'Aplicação'
                                        };
                                ?>
                                    <option value="<?= $v['tipo']; ?>"><?= $acao; ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <div class="col-2">
                            <label for="idProprietario">Proprietário</label>
                            <select class="form-select" id="idProprietario" name="idProprietario">
                                <option value="">Todos</option>
                                <?php foreach ($lista_proprietarios as $v): ?>
                                    <option value="<?= $v['idProprietario']; ?>"><?= $v['idProprietario'] . ' - ' . $v['proprietario']; ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <div class="col-3 pt-3">
                            <button class="btn btn-primary mt-1" type="submit">Aplicar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="card mt-2">
        <div class="card-header bg-dark text-white">
            <h6 class="card-title mb-0">Extrato</h6>
        </div>
        <div class="card-body p-1" id="<?= $div; ?>">
            <?php require ('tabela_extrato.phtml'); ?>
        </div>
    </div>
</div>