<?php
    use MF\Helpers\NumbersHelper;
    $total_orcado = 0;
    $total_proprietarios = [];
    $lista_prop = [];
?>

<div class="container">
    <div class="card mt-2 shadow-sm">
        <div class="card-header bg-primary text-white">
            <h6 class="mb-0">Orçamentos</h6>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-sm table-hover mb-0">
                    <thead class="table-light">
                        <tr>
                            <th scope="col" style="width: 10px;"></th>
                            <th scope="col" class="text-center">Mês</th>
                            <th scope="col">Categoria</th>
                            <th scope="col" class="text-right pe-4">Valor</th>
                            <th scope="col" class="text-right pe-4">Proprietário</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($orcamentos as $value): 
                                $total_orcado += $value['totalOrcado']; 
                                $lista_prop[$value['idProprietario']] = $value['proprietario'];

                                 if (isset($total_proprietarios[$value['idProprietario']])) {
                                    $total_proprietarios[$value['idProprietario']] += $value['totalOrcado'];
                                } else {
                                    $total_proprietarios[$value['idProprietario']] = $value['totalOrcado'];
                                }
                        ?>
                            <tr>
                                <td class="text-center">
                                    <input class="mt-1" type="checkbox" name="selectedData[]" value="<?= $value['idOrcamento']; ?>">
                                </td>
                                <td class="text-center"><?= $value['mesOrcado']; ?></td>
                                <td><?= $value['categoria']; ?></td>
                                <td class="text-right pe-4">R$ <?= NumbersHelper::formatUStoBR($value['totalOrcado']); ?></td>
                                <td><?= $lista_prop[$value['idProprietario']]; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot class="fw-bold bg-light">
                         <?php foreach ($total_proprietarios as $id => $valor): ?>
                            <tr>
                                <td colspan="3" class="ps-3">Total <?= $lista_prop[$id]; ?></td>
                                <td class="text-right pe-4">
                                    <?= NumbersHelper::formatUStoBR($valor); ?>
                                </td>
                                <td></td>
                            </tr>
                        <?php endforeach; ?>
                        <tr>
                            <td colspan="3" class="ps-3">Total</td>
                            <td class="text-right pe-4">R$ <?= NumbersHelper::formatUStoBR($total_orcado); ?></td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>