
<?php
    use MF\Helpers\DateHelper;
    use MF\Helpers\NumbersHelper;

    $total = 0;
    $resultado_ext = 0;
    $total_proprietarios = [];
?>

<div class="container">
    <div class="card mt-2">
        <div class="card-header">
            <button class="btn btn-light btn-sm nav-link" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCadRendimento" aria-expanded="false" aria-controls="collapseCadRendimento">
                Cadastrar Rendimento
            </button>
        </div>
        <div class="collapse" id="collapseCadRendimento">
            <div class="card-body p-1">
                <form data-action="<?= $action; ?>" id="idform-crud" class="submit-form-crud-ajax">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-6">
                                <label for="idDataRendimento">Data</label>
                                <input type="date" class="form-control" id="idDataRendimento" name="dataRendimento" required>
                            </div>
                            <div class="col-6">
                                <label for="idValorRendimento">Valor (decimal com ponto)</label>
                                <input type="number" class="form-control" id="idValorRendimento" name="valorRendimento" step=".01" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-6">
                                    <label for="idContaInvest">Conta Invest</label>
                                    <select class="form-select" id="idContaInvest" name="idContaInvest">
                                        <option value="">Selecione</option>
                                    <?php foreach ($invests as $value): ?>
                                        <option value="<?= $value['idContaInvest']; ?>"><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                                </div>
                                <div class="col-6">
                                    <label for="idTipo">Tipo</label>
                                    <select class="form-select" id="idTipo" name="tipo">
                                        <option value="">Selecione</option>
                                        <option value="1">1 - Preju</option>
                                        <option value="2">2 - Lucro</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button id="salvar" type="submit" class="btn btn-success m-1">Salvar</button>
                </form>
            </div>
        </div>
    </div>

    <div class="card mt-1">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm">
                    <theader>
                        <tr>
                            <th>Banco</th>
                            <th>Título</th>
                            <th>Objetivos</th>
                            <th>Saldo atual</th>
                            <th class="bg-secondary">Saldo anterior</th>
                            <th class="bg-secondary">Data anterior</th>
                        </tr>
                    </theader>
                    <tbody>
                        <?php 
                            foreach ($contas as $value): 
                                $total += $value['saldoAtual'];
                                $lista_prop[$value['idProprietario']] = $value['proprietario'];

                                if (isset($total_proprietarios[$value['idProprietario']])) {
                                    $total_proprietarios[$value['idProprietario']] += $value['saldoAtual'];
                                } else {
                                    $total_proprietarios[$value['idProprietario']] = $value['saldoAtual'];
                                }
                        ?>
                            <tr>
                                <td><?= $value['nomeBanco']; ?></td>
                                <td><?= $value['tituloInvest']; ?></td>
                                <td class="text-left">
                                    <button class="render-ajax" 
                                            data-url="<?= $url_obj . $value['idContaInvest'] ?>"
                                            data-div=""
                                            data-modal="true"
                                    >&#8505;</button>
                                </td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($value['saldoAtual']); ?></td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($value['saldoAnterior']); ?></td>
                                <td><?= DateHelper::convertUStoBR($value['dataAnterior']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr class="table-dark">
                            <td colspan="3" style="text-align: right">Total</td>
                            <td>R$ <?= NumbersHelper::formatUStoBR($total); ?>
                            <td>
                                <?php foreach ($total_proprietarios as $id => $valor): ?>
                                    <small>
                                        <?= $lista_prop[$id]; ?>: <?= NumbersHelper::formatUStoBR($valor); ?>
                                    </small> <br>
                                <?php endforeach; ?>
                            </td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <?php
        $arr = [];
        $total = 0;
        foreach ($objs as $value) {
            if (isset($arr[$value['nomeObj']])) {
                $arr[$value['nomeObj']]['saldo'] += $value['saldoAtual'];
                $arr[$value['nomeObj']]['meta'] += $value['vlrObj'];
            } else {
                $arr[$value['nomeObj']]['saldo'] = $value['saldoAtual'];
                $arr[$value['nomeObj']]['meta'] = $value['vlrObj'];
            }

            $total += $value['saldoAtual'];
        }
    ?>
    <div class="card mt-1">
        <div class="card-body">
            <div class="row">
                <div class="col-9">
                    <table class="table table-sm">
                        <theader>
                            <tr>
                                <th>Objetivo</th>
                                <th>Valor</th>
                                <th>Meta</th>
                                <th>% ating.</th>
                            </tr>
                        </theader>
                        <tbody>
                        <?php 
                            foreach ($arr as $k => $val): ?>
                            <tr>
                                <td><?= $k; ?></td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($val['saldo']); ?></td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($val['meta']); ?></td>
                                <td><?= NumbersHelper::formatUStoBR(number_format(($val['saldo'] / $val['meta']) * 100, 2)); ?>%</td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                            <tr class="table-dark">
                                <td>Total:</td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($total); ?></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-1">
        <div class="card-body">
            <div class="row">
                <div class="col-9">
                    <table class="table table-sm">
                        <theader>
                            <tr>
                                <th>Investimento</th>
                                <th>Projeção rendimento AM R$</th>
                            </tr>
                        </theader>
                        <tbody>
                        <?php 
                            foreach ($arr_projecao as $val): ?>
                            <tr>
                                <td><?= $val['nomeBanco'] . ' ' . $val['tituloInvest']; ?></td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($val['ultimoRendimentoAM']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>