
<?php
    use MF\Helpers\DateHelper;
    use MF\Helpers\NumbersHelper;

    $total = 0;
    $resultado_ext = 0;
    $total_proprietarios = [];
?>

<div class="container">

    <div class="mt-2 mb-2">
		<div class="card p-2">
			<div class="text-center">Investimentos</div>
		</div>
	</div>

    <div class="card mt-2">
        <div class="card-header bg-dark text-white">
            <button class="btn btn-sm nav-link" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCadRendimento" aria-expanded="false" aria-controls="collapseCadRendimento">
                <h6 class="card-title mb-0">Cadastrar Rendimento</h6>
            </button>
        </div>
        <div class="collapse" id="collapseCadRendimento">
            <div class="card-body p-1">
                <form data-action="<?= $action; ?>" id="idform-crud" class="submit-form-crud-ajax">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <label for="idDataRendimento">Data</label>
                                <input type="date" class="form-control" id="idDataRendimento" name="dataRendimento" required>
                            </div>
                            <div class="col-12 col-sm-4">
                                <label for="idContaInvest">Conta Invest</label>
                                    <select class="form-select" id="idContaInvest" name="idContaInvest">
                                        <option value="">Selecione</option>
                                    <?php foreach ($invests as $value): ?>
                                        <option value="<?= $value['idContaInvest']; ?>"><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="col-12 col-sm-4">
                                <label for="idValorAtual">Valor atual do investimento</label>
                                <input type="text" class="form-control numero-br" id="idValorAtual" name="valorAtual" value="0,00" required>
                            </div>
                        </div>
                    </div>
                    <button id="salvar" type="submit" class="btn btn-success m-1">Salvar</button>
                </form>
            </div>
        </div>
    </div>

    <div class="card mt-2 mb-2">
        <div class="card-header bg-dark text-white">
            <h6 class="card-title mb-0">Investimentos ativos</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm">
                    <theader>
                        <tr>
                            <th>Banco</th>
                            <th>Título</th>
                            <th>Objetivos</th>
                            <th>Saldo atual</th>
                            <th>Saldo anterior</th>
                            <th>Data anterior</th>
                            <th>Data resgate</th>
                            <th>Saldo final esperado</th>
                        </tr>
                    </theader>
                    <tbody>
                        <?php 
                            foreach ($invests as $value): 
                                $total += $value['saldoAtual'];
                                $lista_prop[$value['idProprietario']] = $value['proprietario'];

                                if (isset($total_proprietarios[$value['idProprietario']])) {
                                    $total_proprietarios[$value['idProprietario']] += $value['saldoAtual'];
                                } else {
                                    $total_proprietarios[$value['idProprietario']] = $value['saldoAtual'];
                                }
                        ?>
                            <tr>
                                <td><?= $value['nomeBanco']; ?></td>
                                <td><?= $value['tituloInvest']; ?></td>
                                <td class="text-left">
                                    <button class="render-ajax" 
                                            data-url="<?= $url_obj . $value['idContaInvest'] ?>"
                                            data-div=""
                                            data-modal="true"
                                    >&#8505;</button>
                                </td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($value['saldoAtual']); ?></td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($value['saldoAnterior']); ?></td>
                                <td><?= DateHelper::convertUStoBR($value['dataAnterior']); ?></td>
                                <td><?= $value['dataResgatar'] != '0000-00-00' ? DateHelper::convertUStoBR($value['dataResgatar']) : 'N/a'; ?></td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($value['saldoFinal']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr class="table-info">
                            <td colspan="3" style="text-align: right">Total</td>
                            <td>R$ <?= NumbersHelper::formatUStoBR($total); ?>
                            <td>
                                <?php foreach ($total_proprietarios as $id => $valor): ?>
                                    <small>
                                        <?= $lista_prop[$id]; ?>: <?= NumbersHelper::formatUStoBR($valor); ?>
                                    </small> <br>
                                <?php endforeach; ?>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 col-12">
            <?php
                $arr = [];
                $total = 0;
                foreach ($objs as $value) {
                    if (isset($arr[$value['nomeObj']])) {
                        $arr[$value['nomeObj']]['saldo'] += $value['saldoAtual'];
                        $arr[$value['nomeObj']]['meta'] += $value['vlrObj'];
                    } else {
                        $arr[$value['nomeObj']]['saldo'] = $value['saldoAtual'];
                        $arr[$value['nomeObj']]['meta'] = $value['vlrObj'];
                    }

                    $total += $value['saldoAtual'];
                }
            ?>
            <div class="card mb-2">
                <div class="card-header bg-dark text-white">
                    <h6 class="card-title mb-0">Objetivos</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <table class="table table-sm">
                            <theader>
                                <tr>
                                    <th>Objetivo</th>
                                    <th>Valor</th>
                                    <th>Meta</th>
                                    <th>% ating.</th>
                                </tr>
                            </theader>
                            <tbody>
                            <?php 
                                foreach ($arr as $k => $val): ?>
                                <tr>
                                    <td><?= $k; ?></td>
                                    <td>R$ <?= NumbersHelper::formatUStoBR($val['saldo']); ?></td>
                                    <td>R$ <?= NumbersHelper::formatUStoBR($val['meta']); ?></td>
                                    <td><?= NumbersHelper::formatUStoBR(number_format(($val['saldo'] / $val['meta']) * 100, 2)); ?>%</td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="card mb-2">
                <div class="card-header bg-dark text-white">
                    <h6 class="card-title mb-0">Rendimento projetado</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <table class="table table-sm">
                            <theader>
                                <tr>
                                    <th>Investimento</th>
                                    <th>Projeção rendimento AM R$</th>
                                    <th>%</th>
                                </tr>
                            </theader>
                            <tbody>
                            <?php 
                                foreach ($arr_projecao as $val): ?>
                                <tr>
                                    <td><?= $val['nomeBanco'] . ' ' . $val['tituloInvest']; ?></td>
                                    <td>R$ <?= NumbersHelper::formatUStoBR($val['ultimoRendimentoAM']); ?></td>
                                    <td><?= $val['saldoAnterior'] > 0 ? NumbersHelper::formatUStoBR(($val['ultimoRendimentoAM'] / $val['saldoAnterior']) * 100) : '0'; ?>%</td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>