<?php
    echo '<script>var options_obj_origem = ' . $options_list_origem . '</script>';
    echo '<script>var options_obj_destino = ' . $options_list_destino . '</script>';
?>

<input type="hidden" name="tipoMovimento" id="idTipoMovimento" value="<?= $tipo_movimento; ?>">

<?php if ($tipo_movimento == 'transferencia'): ?>
    <div class="mt-2">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h6 class="card-title mb-0">Origem</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-12 col-sm-6 mb-3">
                                    <label for="idContaInvestOrigem">Conta Invest Origem</label>
                                    <select class="form-select exibir-objetivos-origem" id="idContaInvestOrigem" name="idContaInvestOrigem">
                                        <option value="">Selecione</option>
                                        <?php foreach ($invests as $value): ?>
                                            <option value="<?= $value['idContaInvest'] . '@' . $value['idProprietario']; ?>"><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6 mb-3 d-none" id="idSelectObjetivoOrigem">
                                    <label for="idObjetivoOrigem">Objetivo</label>
                                    <select class="form-select" id="idObjetivoOrigem" name="idObjetivoOrigem">
                                        <option value="">Selecione</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-sm-6">
                                    <label for="idValor">Valor transferir (R$)</label>
                                    <input type="number" class="form-control" name="valor" step=".01" value="" id="idValor">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card h-100">
                    <div class="card-header bg-success text-white">
                        <h6 class="card-title mb-0">Destino</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-12 col-sm-6 mb-3">
                                    <label for="idContaInvestDestino">Conta Invest Destino</label>
                                    <select class="form-select exibir-objetivos-destino" id="idContaInvestDestino" name="idContaInvestDestino">
                                        <option value="">Selecione</option>
                                        <?php foreach ($invests as $value): ?>
                                            <option value="<?= $value['idContaInvest'] . '@' . $value['idProprietario']; ?>"><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6 mb-3 d-none" id="idSelectObjetivoDestino">
                                    <label for="idObjetivoDestino">Objetivo</label>
                                    <select class="form-select" id="idObjetivoDestino" name="idObjetivoDestino">
                                        <option value="">Selecione</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php else: 
    $ds = DIRECTORY_SEPARATOR;
    require __DIR__ . "..{$ds}..{$ds}movimentos{$ds}movimentos.phtml";
endif; ?>