<div class="card">
    <div class="card-header bg-dark text-white">
        <h6 class="card-title mb-0">Lista</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-sm table-hover">
                <thead class="table-primary">
                    <tr>
                        <th>Banco</th>
                        <th>Título</th>
                        <th>Proprietário</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($todas_contas as $k => $v): ?>
                        <tr>
                            <td><?= $v['nomeBanco']; ?></td>
                            <td><?= $v['tituloInvest']; ?></td>
                            <td><?= $v['proprietario']; ?></td>
                            <td>
                                <select data-url="<?= $extra_url . $v['idContaInvest']; ?>" class="form-control" id="status-<?= $k; ?>" name="status[]" onchange="atualizarStatus(this)">
                                    <option value="1" <?= $v['status'] == '1' ? ' selected ' : ''; ?>>Ativo</option>
                                    <option value="0" <?= $v['status'] == '0' ? ' selected ' : ''; ?>>Inativo</option>
                                </select>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>