<div class="card">
    <div class="card-header bg-primary text-white">
        <h6 class="card-title mb-0">Lista</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-sm table-hover">
                <thead class="table-primary">
                    <tr>
                        <th>Objetivo</th>
                        <th>Vlr. Final</th>
                        <th>Conta Invest</th>
                        <th>% da conta atrelado</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
            </table>
        </div>
    </div>
</div>