<div class="card">
    <div class="card-header bg-dark text-white">
        <h6 class="card-title mb-0">Cadastro</h6>
    </div>
    <div class="card-body">
        <div class="form-group">
            <div class="row">
                <div class="col-sm-6 col-12">
                    <label for="idNomeObj">Título</label>
                    <input type="text" class="form-control" id="idNomeObj" name="nomeObj" required>
                </div>
                <div class="col-sm-6 col-12">
                    <label for="idVlrObj">Valor Final Juntar</label>
                    <input type="text" class="form-control numero-br" id="idVlrObj" name="vlrObj" value="0,00" required>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-12 col-sm-6">
                    <label for="idContaInvest">Conta Invest</label>
                    <select class="form-select" id="idContaInvest" name="idContaInvest" required>
                        <option value="">Selecione</option>
                        <?php foreach ($invests as $value): ?>
                            <option value="<?= $value['idContaInvest']; ?>"><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-12 col-sm-6">
                    <label for="idPercentObjContaInvest">% da Conta p/ Objetivo</label>
                    <input type="text" class="form-control numero-br"  id="idPercentObjContaInvest" name="percentObjContaInvest" value="0,00" required>
                </div>
            </div>
        </div>
    </div>
</div>