<script>    
    <?php echo 'let ret = ' . $ret . ';'; ?>

    let mes_ano = Array();
    let arr_valores = Array();
    let arr_mes_ano = Array();
    let obj = Object();
    let final = Array();

    for (const item of ret) {
        let index = mes_ano.indexOf(item.mesAno);
        let index2 = arr_valores.indexOf(item.idContaInvest);

        if (index == -1) {
            mes_ano.push(item.mesAno);
        }

        if (index2 == -1) {
            arr_valores[item.idContaInvest] = Array();
            arr_mes_ano[item.idContaInvest] = Array();
        }
    }

    for (const item of ret) {
        arr_valores[item.idContaInvest].push(item.valor);
        arr_mes_ano[item.idContaInvest].push(item.mesAno);
    }

    arr_valores.forEach(function (v, id) {
        obj = {
            id: id,
            mes: arr_mes_ano[id],
            valor: v
        };

        final.push(obj);
    })

    console.log(final);

    // console.log(mes_ano);
    // console.log(arr_valores);
    // console.log(arr_mes_ano);
    // console.log(arr_valores);
</script>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div class="container">
    <canvas id="myChart"></canvas>
</div>

<script>
    const ctx = document.getElementById('myChart');

    const labels = mes_ano;
    const data = {
        labels: labels,
        datasets: arr_data
    };

  new Chart(ctx, {
    type: 'line',
    data: data,
    options: {
        responsive: true,
        plugins: {
          legend: {
              position: 'top',
          },
          title: {
              display: true,
              text: 'Chart.js Line Chart'
          }
        }
    },
    options: {
      scales: {
        y: {
          beginAtZero: false
        }
      }
    }
  });
</script>