<div class="modal-header p-2">
    <h1 class="modal-title fs-5" id="modal-conteudo-titulo"><?= $this->view->titulo; ?></h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body" id="modal-conteudo-conteudo">
    <?php foreach ($data as $prop => $tipo): ?>
        <table class="table table-sm">
            <thead>
                <tr>
                    <th colspan="100%"><?= ($prop == '1' ? 'Luiz' : 'Uepa'); ?></th>
                </tr>
                <tr>
                    <th style="width: 40%">Descrição</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tipo as $k => $val): ?>
                    <tr>
                        <td><?= $k; ?></td>
                        <td>
                            <?= $val; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr class="table-active">
                        <td>Receitas - Despesas - Resgates</td>
                        <td><?= (abs(($total_receita[$prop] ?? 0)) - abs(($total_despesa[$prop] ?? 0)) - abs(($total_resgate[$prop] ?? 0))); ?></td>
                    </tr>
                    <tr class="table-active">
                        <td>Aplicação - Resgates</td>
                        <td><?= (abs(($total_aplicacao[$prop] ?? 0)) - abs(($total_resgate[$prop] ?? 0))); ?></td>
                    </tr>
                    <tr class="table-active">
                        <td>Receitas - Despesas</td>
                        <td><?= (abs(($total_receita[$prop] ?? 0)) - abs(($total_despesa[$prop] ?? 0))); ?></td>
                    </tr>
                </tfoot>
            </table>
    <?php endforeach; ?>
</div>