<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Data</th>
                <th>Descrição</th>
                <th>Prop.</th>
                <th>Valor</th>
                <th>Categoria</th>
            </tr>
        </thead>
        <tbody> 
            <?php 
                foreach ($arr_mensais as $value): 
                    $dia_original = date('d', strtotime($value['dataRepete']));
                    $mes_original = date('m', strtotime($value['dataRepete']));
                    $ano_original = date('Y', strtotime($value['dataRepete']));
                    $mes_atual = date('m');
                    $ano_atual = date('Y');

                    $date = date_format(date_create("$ano_atual-$mes_atual-$dia_original"), 'Y-m-d');
            ?>
                <tr class="<?= ($value['idPago'] > 0 ? ' bg-pago ' : (date('Y-m-d') >= $date ? ' bg-atencao ' : '')); ?>">
                    <td>
                        <input type="checkbox" value="<?= $value['idMovMensal']; ?>" name="idMovMensal[]" <?= ($value['idPago'] > 0 ? ' disabled ' : ''); ?>>
                    </td>
                    <td>
                        <input type="date" id="idDataMovimento" name="dataMovimento[<?= $value['idMovMensal']; ?>]" value="<?= $date; ?>">
                    </td>
                    <td>
                        <?= $value['nomeMovimento']; ?>
                        <input type="hidden" name="nomeMovimento[<?= $value['idMovMensal']; ?>]" value="<?= $value['nomeMovimento']; ?>">
                    </td>
                    <td>
                        <select class="form-select" id="idProprietario" name="proprietario[<?= $value['idMovMensal']; ?>]">
                            <option value="1">Luiz</option>
                            <option value="2" <?= $value['proprietario'] == '2' ? ' selected ' : ''; ?>>Uepa</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" class="form-control"  name="valor[<?= $value['idMovMensal']; ?>]" step=".01" value="<?= $value['valorDespesa']; ?>">
                    </td>
                    <td>
                        <?= $value['idCategoria'] . ' - ' . $value['categoria'] . ' - ' . $value['tipo']; ?>
                        <input type="hidden" name="idCategoria[<?= $value['idMovMensal']; ?>]" value="<?= $value['idCategoria'] . ' - sinal: ' . $value['sinal']; ?>">
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>