
<?php
    echo '<script>var options_obj = ' . $options_list . '</script>';
    $id_obj_old = 0;
?>

<?php if (isset($movimento['idMovimento'])) { ?>
    <input type="hidden" name="idMovimento" value="<?= $movimento['idMovimento']; ?>">
    <input type="hidden" name="idObjOld" value="<?= $movimento['idObj']; ?>">

    <?php
        if (!empty($movimento['idObj'])) 
            $id_obj_old = $movimento['idObj']; $obj_old_name = $movimento['nomeObj'];
    } ?>

<div class="form-group">
    <div class="row">
        <div class="col-12 col-sm-6">
            <label for="idNomeMovimento">Nome Movimento</label>
            <input type="text" class="form-control" id="idNomeMovimento" name="nomeMovimento" required value="<?= $movimento['nomeMovimento'] ?? ''; ?>">
        </div>
        <div class="col-12 col-sm-3">
            <label for="idDataMovimento">Data Movimento (m/d/a)</label>
            <input type="date" class="form-control" id="idDataMovimento" name="dataMovimento" required value="<?= $movimento['dataMovimento'] ?? ''; ?>">
        </div>
        <div class="col-12 col-sm-3">
            <label for="idCategoria">Categoria</label>
            <select class="form-select exibir-objetivos" id="idCategoria" name="idCategoria" required>
                <option value="">Selecione</option>
                <?php foreach ($categorias as $cat): ?>
                    <?php if (!empty($movimento) && $movimento['idCategoria'] == $cat['idCategoria']): ?>
                        <option value="<?= $cat['idCategoria'] . ' - sinal: ' . $cat['sinal']; ?>" selected><?= $cat['categoria'] . ' - ' . $cat['tipo']; ?></option>
                    <?php else: ?>
                        <option value="<?= $cat['idCategoria'] . ' - sinal: ' . $cat['sinal']; ?>"><?= $cat['categoria'] . ' - ' . $cat['tipo']; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-3">
                <label for="tipo">Valor (EUA e apenas inteiro)</label>
                <input type="number" class="form-control" id="idValor" name="valor" required value="<?= $movimento['valor'] ?? ''; ?>">
            </div>
            <div class="col-3">
                <label for="idProprietario">Proprietário</label>
                <select class="form-select" id="idProprietario" name="proprietario">
                    <option value="1" <?= (!empty($movimento) && $movimento['proprietario'] == '1' ? ' selected ' : ''); ?>>Luiz</option>
                    <option value="2" <?= (!empty($movimento) && $movimento['proprietario'] == '2' ? ' selected ' : ''); ?>>Uepa</option>
                </select>
            </div>
            <div class="col-3">
                <label for="idContaInvest">Conta Invest (se houver)</label>
                <select class="form-select exibir-objetivos" id="idContaInvest" name="idContaInvest">
                    <option value="">Selecione</option>
                    <?php foreach ($invests as $value): ?>
                        <?php if (!empty($movimento) && $movimento['idContaInvest'] == $value['idContaInvest']): ?>
                            <option value="<?= $value['idContaInvest']; ?>" selected><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                        <?php else: ?>
                            <option value="<?= $value['idContaInvest']; ?>"><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-3 <?= $id_obj_old != '0' ? 'd-block' : 'd-none'; ?>" id="idSelectObjetivo">
                <label for="idObjetivo">Conta Invest (se houver)</label>
                <select class="form-select" id="idObjetivo" name="idObjetivo">
                    <option value="">Selecione</option>
                    <?php if ($id_obj_old != 0): ?>
                        <option value="<?= $id_obj_old; ?>" selected><?= $id_obj_old . ' - ' . $obj_old_name; ?></option>
                    <?php endif; ?>
                </select>
            </div>
            <!-- <div class="col-6 mt-4">
                <label for="tipo">No Cartão?</label>
                <input type="checkbox" id="idCartao" name="cartao" value="1">
            </div> -->
        </div>
    </div>
</div>