<?php use MF\Helpers\NumbersHelper; ?>

<div class="modal-header p-2">
    <h1 class="modal-title fs-5" id="modal-conteudo-titulo"><?= $this->view->titulo; ?></h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body" id="modal-conteudo-conteudo">
    <table class="table">
        <thead>
            <tr>
                <th>id</th>
                <th>Nome</th>
                <th>Vlr. objetivo</th>
                <th>% da conta</th>
                <th>Saldo atual</th>
                <th>Criação</th>
            </tr>
        </thead>
        <tbody>
            <?php 
                $total = 0;
                $total_obj = 0;
                $total_percent = 0;
                foreach ($lista_objetivos as $value): 
                    $total += $value['saldoAtual'];
                    $total_obj += $value['vlrObj'];
                    $total_percent += $value['percentObjContaInvest'];
            ?>
                <tr>
                    <td><?= $value['idObj']; ?></td>
                    <td><?= $value['nomeObj']; ?></td>
                    <td>R$ <?= NumbersHelper::formatUStoBR($value['vlrObj']); ?></td>
                    <td><?= NumbersHelper::formatUStoBR($value['percentObjContaInvest']); ?></td>
                    <td>R$ <?= NumbersHelper::formatUStoBR($value['saldoAtual']); ?></td>
                    <td><?= $value['dataCriacao']; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">Total</td>
                <td>R$ <?= NumbersHelper::formatUStoBR($total_obj); ?></td>
                <td><?= NumbersHelper::formatUStoBR($total_percent); ?></td>
                <td>R$ <?= NumbersHelper::formatUStoBR($total); ?></td>
            </tr>
        </tfoot>
    </table>
</div>