<div class="card border-0 shadow-sm formulario-padrao-card">
    <div class="card-header bg-dark text-white">
        <div class="d-flex align-items-center">
            <i class="bi bi-plus-circle fs-4 me-2"></i>
            <h6 class="card-title mb-0">Cadastro</h6>
        </div>
    </div>
    <div class="card-body p-2">
        <div class="form-group mb-3">
            <div class="row g-2">
                <div class="col-md-3">
                    <label for="idData" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Data</label>
                    <input type="date" class="form-control formulario-padrao-input" id="idData" name="data" required>
                </div>
                <div class="col-md-3">
                    <label for="idTotalReceitas" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Total de Receitas</label>
                    <div class="input-group">
                        <span class="input-group-text bg-light border-end-0">R$</span>
                        <input type="text" class="form-control numero-br formulario-padrao-input" id="idTotalReceitas" name="totalReceitas" required value="0,00">
                    </div>
                </div>
                <div class="col-md-3">
                    <label for="idValorEconomizar" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Valor a Economizar</label>
                    <div class="input-group">
                        <span class="input-group-text bg-light border-end-0">R$</span>
                        <input type="text" class="form-control numero-br formulario-padrao-input" id="idValorEconomizar" name="vlrEconomizar" required value="0,00">
                    </div>
                </div>
                <div class="col-md-3">
                    <label for="idProprietario" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Proprietário</label>
                    <select class="form-select formulario-padrao-input" id="idProprietario" name="idProprietario" required>
                        <?php 
                            foreach ($lista_proprietarios as $prop):
                                $x = $prop['idProprietario'];
                                $n = $prop['proprietario'];
                        ?>
                            <option value="<?= $x ?>"> <?= $n; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>