<div class="container">
    <div class="mt-2 mb-2">
        <div class="card p-2">
            <div class="text-center">Metas Mensais</div>
        </div>
    </div>

    <div class="row my-2">
        <div class="col-12">
            <div class="card border-0 shadow-sm formulario-padrao-card">
                <div class="card-header bg-dark text-white">
                    <div class="d-flex align-items-center">
                        <i class="bi bi-filter fs-4 me-2"></i>
                        <h6 class="card-title mb-0">Filtro</h6>
                    </div>
                </div>
                <div class="card-body p-2">
                    <form method="POST" data-action="<?= $url; ?>" class="form-inline submit-form-render-ajax" data-div="<?= $div; ?>">
                        <div class="form-group">
                            <div class="row g-2">
                                <div class="col-md-6">
                                    <label for="idProprietario" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Proprietário</label>
                                    <select class="form-select formulario-padrao-input" id="idProprietario" name="idProprietario">
                                        <option value="">Selecione</option>
                                        <?php
                                            foreach ($lista_proprietarios as $prop):
                                                $x = $prop['idProprietario'];
                                                $n = $prop['proprietario'];
                                        ?>
                                            <option value="<?= $x ?>"> <?= $n; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>

                                <div class="col-md-6">
                                    <label for="idAno" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Ano</label>
                                    <select class="form-select formulario-padrao-input" id="idAno" name="ano">
                                        <option value="2023">2023</option>
                                        <option value="2024">2024</option>
                                        <option value="2025">2025</option>
                                        <option value="2026" selected>2026</option>
                                        <option value="2027">2027</option>
                                    </select>
                                </div>
                            </div>

                            <div class="mt-1"> 
                                <button id="salvar" type="submit" class="btn btn-success m-1">Aplicar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="<?= $div; ?>"></div>
</div>