<div class="container">
    <div class="mt-2 mb-2">
        <div class="card p-2">
            <div class="text-center">Metas Mensais</div>
        </div>
    </div>

    <div class="row my-2">
        <div class="col-12 col-sm-4">
            <div class="card">
                <div class="card-body">
                    <label for="selectProprietario" class="form-label">Filtrar Proprietário</label>
                    <select class="form-select obter-metas-mensais" id="idProprietario" name="idProprietario" data-url="<?= $url; ?>" data-div="<?= $div; ?>">
                        <option value="">Selecione</option>
                        <?php
                            foreach ($lista_proprietarios as $prop):
                                $x = $prop['idProprietario'];
                                $n = $prop['proprietario'];
                        ?>
                            <option value="<?= $x ?>"> <?= $n; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="<?= $div; ?>"></div>
</div>