
<div class="form-group">
    <div class="row">
        <div class="col-12 col-sm-4">
            <label for="idDataRepete">Data Repetição (mensal)</label>
            <input type="date" class="form-control" id="idDataRepete" name="dataRepete" required>
        </div>
        <div class="col-12 col-sm-4">
            <label for="idValorDespesa">Valor (decimal com ponto)</label>
            <input type="number" class="form-control" id="idValorDespesa" name="valorDespesa" step=".01" required>
        </div>
        <div class="col-12 col-sm-4">
            <label for="idCategoria">Categoria</label>
            <select class="form-select" id="idCategoria" name="idCategoria" required>
                <option value="">Selecione</option>
                <?php foreach ($categorias as $cat): ?>
                    <option value="<?= $cat['idCategoria'] . ' - sinal: ' . $cat['sinal']; ?>"><?= $cat['categoria'] . ' - ' . $cat['tipo']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="row">
        <div class="col-12 col-sm-6">
            <label for="idNomeMovimento">Nome Movimento</label>
            <input type="text" class="form-control" id="idNomeMovimento" name="nomeMovimento" required>
        </div>
        <div class="col-12 col-sm-6">
            <label for="idProprietario">Proprietário</label>
            <select class="form-select" id="idProprietario" name="proprietario">
                <?php foreach ($lista_proprietarios as $prop): ?>
                    <option value="<?= $prop['idProprietario']; ?>"> <?= $prop['proprietario']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>