<div class="form-group p-1">
    <div class="row justify-content-center">
        <div class="col-sm-3 col-12 text-center">
            <button type="button" class="btn btn-dark mt-1 render-ajax" data-url="<?= $url_ajax . 'transferencia'; ?>" data-div="<?= $div_ajax; ?>">Transferência entre contas</button>
        </div>
        <div class="col-sm-3 col-12 text-center">
            <button type="button" class="btn btn-dark mt-1 render-ajax" data-url="<?= $url_ajax .'pagamento'; ?>" data-div="<?= $div_ajax; ?>">Movimento pago com investimento</button>
        </div>
    </div>
</div>

<div id="<?= $div_ajax; ?>"></div>