<div class="form-group p-1">
    <div class="row">
        <div class="col-3">
            <label for="idMesOrigem">Mês origem</label>
            <input type="month" id="idMesOrigem" name="mesOrigem" placeholder="yyyy-mm">
        </div>
        <div class="col-3">
            <label for="idDestino">Mês destino</label>
            <input type="month" id="idDestino" name="destino" placeholder="yyyy-mm">
        </div>
    </div>

    <button type="button" class="btn btn-primary mt-1 obter-orcamentos" data-url="<?= $url_ajax; ?>" data-div="<?= $div_ajax; ?>">Buscar</button>
</div>

<div id="<?= $div_ajax; ?>"></div>