<div class="container">

    <div class="mt-2 mb-2">
		<div class="card p-2">
			<div class="text-center">
				<?= $title; ?>
			</div>
		</div>
	</div>

    <div class="card mt-2">
        <div class="card-header bg-primary text-white">
            <h6 class="card-title mb-0">Filtro</h6>
        </div>
        <div class="card-body">
            <form 
                class="form-inline submit-form-render-ajax"
                data-action="<?= $action; ?>" 
                data-div="<?= $div; ?>"
                method="POST"
            >
                <div class="form-group">
                    <div class="row">
                        <div class="col-12 col-sm-3">
                            <label for="data_inicio">Data Início:</label>
                            <input type="date" class="form-control" id="data_inicio" name="data_inicio">
                        </div>

                        <div class="col-12 col-sm-3">
                            <label for="data_fim">Data Fim:</label>
                            <input type="date" class="form-control" id="data_fim" name="data_fim">
                        </div>

                        <div class="col-12 col-sm-3">
                            <label for="idCategoria">Categoria:</label>
                            <select class="form-control" id="idCategoria" name="idCategoria">
                                <option value="">Selecione</option>
                                <?php foreach ($lista_categorias as $v): ?>
                                    <option value="<?= $v['idCategoria']; ?>"><?= $v['idCategoria'] . ' - ' . $v['categoria']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        
                        <div class="col-12 col-sm-3">
                            <label for="idProprietario">Proprietário:</label>
                            <select class="form-control" id="idProprietario" name="idProprietario">
                                <option value="">Selecione</option>
                                <?php foreach ($lista_proprietarios as $v): ?>
                                    <option value="<?= $v['idProprietario']; ?>"><?= $v['idProprietario'] . ' - ' . $v['proprietario']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="mt-1"> 
					<button id="salvar" type="submit" class="btn btn-success m-1">Processar</button>
                </div>
            </form>
        </div>
    </div>

    <div id="<?= $div; ?>">
    </div>
</div>