<div class="container">

    <div class="mt-2 mb-2">
		<div class="card p-2">
			<div class="text-center">
				<?= $title; ?>
			</div>
		</div>
	</div>

    <div class="card mt-2 border-0 shadow-sm formulario-padrao-card">
        <div class="card-header bg-dark text-white">
            <div class="d-flex align-items-center">
                <i class="bi bi-filter fs-4 me-2"></i>
                <h6 class="card-title mb-0">Filtro</h6>
            </div>
        </div>
        <div class="card-body p-2">
            <form 
                class="form-inline submit-form-render-ajax"
                data-action="<?= $action; ?>" 
                data-div="<?= $div; ?>"
                method="POST"
            >
                <div class="form-group">
                    <div class="row g-2">
                        <div class="col-md-3">
                            <label for="data_inicio" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Data Início</label>
                            <input type="date" class="form-control formulario-padrao-input" id="data_inicio" name="data_inicio">
                        </div>

                        <div class="col-md-3">
                            <label for="data_fim" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Data Fim</label>
                            <input type="date" class="form-control formulario-padrao-input" id="data_fim" name="data_fim">
                        </div>

                        <div class="col-md-3">
                            <label for="idCategoria" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Categoria</label>
                            <select class="form-select formulario-padrao-input" id="idCategoria" name="idCategoria">
                                <option value="">Selecione</option>
                                <?php foreach ($lista_categorias as $v): ?>
                                    <option value="<?= $v['idCategoria']; ?>"><?= $v['idCategoria'] . ' - ' . $v['categoria']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        
                        <div class="col-md-3">
                            <label for="idProprietario" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Proprietário</label>
                            <select class="form-select formulario-padrao-input" id="idProprietario" name="idProprietario">
                                <option value="">Selecione</option>
                                <?php foreach ($lista_proprietarios as $v): ?>
                                    <option value="<?= $v['idProprietario']; ?>"><?= $v['idProprietario'] . ' - ' . $v['proprietario']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="mt-1"> 
                    <button id="salvar" type="submit" class="btn btn-success m-1">Processar</button>
                </div>
            </form>
        </div>
    </div>

    <div id="<?= $div; ?>">
    </div>
</div>