<div class="card">
    <div class="card-header bg-primary text-white">
        <h6 class="card-title mb-0">Cadastro</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-sm-6">
                <label for="categoria">Nome Proprietario(a)</label>
                <input type="text" class="form-control" id="proprietario" name="proprietario" required>
            </div>
        </div>
    </div>
</div>