<?php
    use MF\Helpers\NumbersHelper;
    $total_real_por_tipo = 0;
    $total_orcado_por_tipo = 0;

    $total_real_geral = 0;
    $total_orcado_geral = 0;
?>

<div class="container mt-3">
    <div class="mt-2 mb-2">
		<div class="card p-2">
			<div class="text-center">
				<?= $title; ?>
			</div>
		</div>
	</div>

    <div class="card border-0 shadow-sm">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="ps-4 fw-bold">Categoria</th>
                            <th class="text-end pe-4 fw-bold">Realizado</th>
                            <th class="text-end pe-4 fw-bold">Orçado</th>
                            <th class="text-end pe-4 fw-bold">Diferença</th>
                            <th class="text-end pe-4 fw-bold">% Atingido</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            foreach ($indicadores as $id => $v):
                                $realizado = $v['totalRealizado'];
                                $orcado = $v['totalOrcado'];
                                $tipo_categoria = $v['tipo'];
                                $next_tipo_categoria = next($indicadores)['tipo'] ?? '';
                                $diferença = abs($realizado) - abs($orcado);

                                $total_real_geral += $realizado;
                                $total_orcado_geral += $orcado;
                        ?>
                            <tr class="<?= $tipo_categoria != $next_tipo_categoria ? 'border-bottom border-dark' : '' ?>">
                                <td class="ps-4"><?= $v['categoria']; ?></td>
                                <td class="text-end fw-bold pe-4"><?= NumbersHelper::formatUStoBR($realizado); ?></td>
                                <td class="text-end fw-bold pe-4"><?= NumbersHelper::formatUStoBR($orcado); ?></td>
                                <td class="text-end pe-4"><?= NumbersHelper::formatUStoBR($diferença); ?></td>
                                <td class="text-end pe-4">
                                    <?= (abs($realizado) > 0 && abs($orcado) > 0 ? NumbersHelper::formatUStoBR($realizado / $orcado * 100) . '%' : '0,00%'); ?>
                                </td>
                            </tr>
                            <?php if ($tipo_categoria != $next_tipo_categoria): ?>
                                <tr class="table-info">
                                    <td class="ps-4 fw-bold">Total <?= $tipo_categoria; ?></td>
                                    <td class="ps-4 fw-bold text-end"><?= $arr_totais_por_tipo[$tipo_categoria]; ?></td>
                                    <td class="ps-4 fw-bold text-end"><?= $arr_totais_por_tipo_orcado[$tipo_categoria]; ?></td>
                                    <td colspan="2"></td>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <?php
                            $divisao = $total_orcado_geral != 0 ? $total_real_geral / $total_orcado_geral : 0;
                        ?>
                        <tr class="table-dark fw-bolder">
                            <td class="ps-4">Total Geral</td>
                            <td class="text-end <?= $total_real_geral <= 0 ? 'text-danger' : 'text-success'; ?> fw-bold pe-4"><?= NumbersHelper::formatUStoBR($total_real_geral); ?></td>
                            <td class="text-end <?= $total_orcado_geral <= 0 ? 'text-danger' : 'text-success'; ?> fw-bold pe-4"><?= NumbersHelper::formatUStoBR($total_orcado_geral); ?></td>
                            <td class="text-end pe-4">
                                <?= NumbersHelper::formatUStoBR($total_real_geral - $total_orcado_geral); ?>
                            </td>
                            <td class="text-end <?= ($divisao > 0.8 && $divisao < 1.2 ? 'text-success' : 'text-danger'); ?> pe-4">
                                <?= NumbersHelper::formatUStoBR(($divisao) * 100) . '%'; ?>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>