<div class="col">
    <div class="card border-start border-start-5 border-start-primary h-100">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h6 class="text-muted text-uppercase small">Disponível em CC</h6>
                    <h5 class="mb-0 fw-bold">R$ <?= $data_saldo['saldo'] ?></h5>
                </div>
            </div>
        </div>
    </div>
</div>