<?php 
    use MF\Helpers\DateHelper;
    use MF\Helpers\NumbersHelper;

    $acumulado = 0;
    $resultado_invests = 0;
?>

<div class="container">
    <div class="row mb-4">
        <div class="col-md-4 mb-3">
            <div class="">
                <?php $this->renderCardReceitas(); ?>
            </div>
        </div>
        <div class="col-md-4 mb-3">
            <div class="">
                <?php $this->renderCardDespesas(); ?>
            </div>
        </div>
        <div class="col-md-4 mb-3">
            <div class="">
                <?php $this->renderCardSaldo(); ?>
            </div>
        </div>
    </div>

    <div class="card mt-1">
        <div class="card-header d-flex justify-content-between align-items-center py-1">
            <span><i class="bi bi-list-check"></i>Todos</span>
            <a href="movimentos" class="link-offset-2 link-underline link-underline-opacity-0">
                <button class="btn btn-sm btn-light">Novo</button>
            </a>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-striped table-hover table-sm mb-1 align-middle">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Movimento</th>
                            <th>Categoria</th>
                            <th>Valor</th>
                            <th>Prop.</th>
                            <th style="width: 5%;">Editar</th>
                            <th style="width: 3%;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (empty($prop)): ?>
                            <tr><td colspan="7" class="text-center">Sem movimentos para o período/filtro.</td></tr>
                        <?php else: ?>
                            <?php foreach ($movimentos_agrupados as $data => $lancamentosDoDia): ?>
                                <tr class="bg-light bg-opacity-50 lh-1">
                                    <td colspan="7" class="p-1 text-white bg-dark small">
                                        <?= $data ?>
                                    </td>
                                </tr>

                                <?php foreach ($lancamentosDoDia as $mov): ?>
                                    <tr>
                                        <td>
                                            <button title="Detalhes" 
                                                    class="btn btn-sm btn-primary render-ajax" 
                                                    data-url="<?= $url_detail . $mov['idMovimento']; ?>" 
                                                    data-div=""
                                                    data-modal="true">
                                                &#128489;
                                            </button>
                                        </td>
                                        <td>
                                            <?= $mov['nomeMovimento']; ?>
                                        </td>
                                        <td><?= $mov['categoria']; ?></td>
                                        <td>R$ <?= NumbersHelper::formatUStoBR($mov['valor']); ?></td>
                                        <td><?= $prop[$mov['idProprietario']]; ?></td>
                                        <td>
                                            <a href="<?= $url_edit . $mov['idMovimento']; ?>" class="link-offset-2 link-underline link-underline-opacity-0">
                                                <button title="Editar" class="btn btn-sm btn-dark">
                                                    <i>&#9998;</i>
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <input type="checkbox" name="selectedData[]" value="<?= $mov['idMovimento']; ?>">
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                    <tfoot>
                        <tr class="table-info">
                            <td></td>
                            <td colspan="2" style="text-align: right">Resultado (Rec. - Des. - Apli.)</td>
                            <td>R$ <?= NumbersHelper::formatUStoBR($resultado); ?></td>
                            <td>
                                <?php foreach ($result_por_prop as $id_prop => $valor): ?>
                                    <small><?= $prop[$id_prop]; ?>: <?= NumbersHelper::formatUStoBR($valor); ?></small> <br>
                                <?php endforeach; ?>
                            </td>
                            <td colspan="2"></td>
                        </tr>
                        <?php 
                            if (!empty($saldos_anteriores)): 
                                $acumulado = $resultado;
                        ?>
                            <?php 
                                foreach ($saldos_anteriores as $value): 
                                    $acumulado += $value['valor'];
                            ?>
                                <tr class="table-info">
                                    <td></td>
                                    <td colspan="2" style="text-align: right">Resultado mês <?= $value['MES']; ?>:</td>
                                    <td>R$ <?= NumbersHelper::formatUStoBR($value['valor']); ?></td>
                                    <td colspan="3"></td>
                                </tr>
                            <?php endforeach; ?>
                                <tr class="table-info">
                                    <td></td>
                                    <td colspan="2" style="text-align: right">Acumulado</td>
                                    <td>R$ <?= NumbersHelper::formatUStoBR($acumulado); ?></td>
                                    <td colspan="3"></td>
                                </tr>
                        <?php endif; ?>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <div class="card mt-2">
        <div class="card-header d-flex justify-content-between align-items-center py-1">
            <span><i class="bi bi-graph-up"></i>Investimentos</span>
            <div>
                <a href="contas-investimentos-index" class="link-offset-2 link-underline link-underline-opacity-0">
                    <button class="btn btn-sm btn-light">Novo</button>
                </a>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-striped table-hover table-sm mb-1 align-middle">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Tipo</th>
                            <th>Conta</th>
                            <th>Valor</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                            foreach ($mov_investimentos as $mov): 
                                $resultado_invests += $mov['valor'];
                        ?>
                            <tr>
                                <td><?= DateHelper::convertUStoBR($mov['dataMovimento']); ?></td>
                                <td><?= explode(' ', $mov['categoria'])[0]; ?></td>
                                <td><?= $mov['invest']; ?></td>
                                <td>R$ <?= NumbersHelper::formatUStoBR($mov['valor']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr class="table-info">
                            <td colspan="3" style="text-align: right">Acumulado</td>
                            <td>R$ <?= NumbersHelper::formatUStoBR($resultado_invests); ?></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>