<div class="container">
    <div class="card mt-2">
        <div class="card-body">
            <form 
                class="form-inline submit-form-render-ajax"
                data-action=""
                data-div=""
                method="POST"
            >
                <div class="form-group">
                    <div class="row">
                        <div class="col-12 col-sm-3">
                            <label for="data_inicio">Data Início:</label>
                            <input type="date" class="form-control" id="data_inicio" name="data_inicio">
                        </div>

                        <div class="col-12 col-sm-3">
                            <label for="data_fim">Data Fim:</label>
                            <input type="date" class="form-control" id="data_fim" name="data_fim">
                        </div>
                        
                        <div class="col-12 col-sm-3">
                            <label for="idCategoria">Categoria:</label>
                            <select class="form-control" id="idCategoria" name="idCategoria">
                                <!-- As opções serão preenchidas via PHP -->
                            </select>
                        </div>
                        
                        <div class="col-12 col-sm-3">
                            <label for="idProprietario">Proprietário:</label>
                            <select class="form-control" id="idProprietario" name="idProprietario">
                                <!-- As opções serão preenchidas via PHP -->
                            </select>
                        </div>
                    </div>
                </div>
                <div class="mt-1"> 
					<button id="salvar" type="submit" class="btn btn-success m-1">Processar</button>
                </div>
            </form>
        </div>
    </div>

    <div id="content-extrato-proprietarios">
        <?php include ('extrato_proprietarios.phtml'); ?>
    </div>
</div>