<?php
    use MF\Helpers\NumbersHelper;

    if (isset($options_list)) {
        echo '<script>var options_obj = ' . $options_list . '</script>';
    } else {
        echo '<script>var options_obj = ' . $options_list_destino . '</script>';
    }

    $id_obj_old = 0;
    $mov_id_proprietario = null;
?>

<?php if (isset($movimento['idMovimento'])) { ?>
    <input type="hidden" name="idMovimento" value="<?= $movimento['idMovimento']; ?>">
    <input type="hidden" name="idObjOld" value="<?= $movimento['idObj']; ?>">

    <?php
        if (!empty($movimento['idObj'])) 
            $id_obj_old = $movimento['idObj']; $obj_old_name = $movimento['nomeObj'];

        if (!empty($movimento['idProprietario']))
            $mov_id_proprietario = $movimento['idProprietario'];
} ?>


<div class="card border-0 shadow-sm formulario-padrao-card">
    <div class="card-header bg-dark text-white">
        <div class="d-flex align-items-center">
            <i class="bi bi-plus-circle fs-4 me-2"></i>
            <h6 class="card-title mb-0"><?= $titulo_card; ?></h6>
        </div>
    </div>
    <div class="card-body p-2">
        <div class="row g-2">
            <div class="col-md-6">
                <label for="idNomeMovimento" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Nome Movimento</label>
                <div class="input-group">
                    <input 
                        type="text" 
                        class="form-control formulario-padrao-input" 
                        id="idNomeMovimento" 
                        name="nomeMovimento" required 
                        value="<?= $movimento['nomeMovimento'] ?? ''; ?>"
                        data-action="<?= $url_buscar_mov_mensal; ?>"
                        data-div="<?= $div_buscar_mov_mensal; ?>"
                    >
                </div>
                <div id="<?= $div_buscar_mov_mensal; ?>"></div>
            </div>
            <div class="col-md-3">
                <label for="idDataMovimento" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Data Movimento (m/d/a)</label>
                <div class="input-group">
                    <input type="date" class="form-control formulario-padrao-input" id="idDataMovimento" name="dataMovimento" required value="<?= $movimento['dataMovimento'] ?? ''; ?>">
                </div>
            </div>
            <div class="col-md-3">
                <label for="idCategoria" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Categoria</label>
                <select class="form-select exibir-objetivos formulario-padrao-input" id="idCategoria" name="idCategoria" required>
                    <option value="">Selecione</option>
                    <?php foreach ($categorias as $cat): ?>
                        <?php if (!empty($movimento) && $movimento['idCategoria'] == $cat['idCategoria']): ?>
                            <option value="<?= $cat['idCategoria'] . ' - sinal: ' . $cat['sinal']; ?>" selected><?= $cat['categoria'] . ' - ' . $cat['tipo']; ?></option>
                        <?php else: ?>
                            <option value="<?= $cat['idCategoria'] . ' - sinal: ' . $cat['sinal']; ?>"><?= $cat['categoria'] . ' - ' . $cat['tipo']; ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-3">
                <label for="idValor" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Valor</label>
                <div class="input-group">
                    <span class="input-group-text bg-light border-end-0">R$</span>
                    <input type="text" class="form-control numero-br formulario-padrao-input" id="idValor" name="valor" required value="<?= NumbersHelper::formatUStoBR($movimento['valor'] ?? '0,00'); ?>">
                </div>
            </div>
            <div class="col-md-3">
                <label for="idProprietario" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Proprietário</label>
                <select class="form-select formulario-padrao-input" id="idProprietario" name="idProprietario">
                    <?php 
                        foreach ($lista_proprietarios as $prop):
                            $x = $prop['idProprietario'];
                            $n = $prop['proprietario'];
                    ?>
                        <option value="<?= $x ?>" <?= $mov_id_proprietario == $x ? ' selected ' : ''; ?>> <?= $n; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-md-3">
                <label for="idContaInvest" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Conta Invest (se houver)</label>
                <select class="form-select exibir-objetivos formulario-padrao-input" id="idContaInvest" name="idContaInvest">
                    <option value="">Selecione</option>
                    <?php foreach ($invests as $value): ?>
                        <?php if (!empty($movimento) && $movimento['idContaInvest'] == $value['idContaInvest']): ?>
                            <option value="<?= $value['idContaInvest']; ?>" selected><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                        <?php else: ?>
                            <option value="<?= $value['idContaInvest']; ?>"><?= $value['nomeBanco'] . ' - ' . $value['tituloInvest']; ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-md-3 <?= $id_obj_old != 0 ? 'd-block' : 'd-none'; ?>" id="idSelectObjetivo">
                <label for="idObjetivo" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Objetivo (se houver)</label>
                <select class="form-select formulario-padrao-input" id="idObjetivo" name="idObjetivo">
                    <option value="">Selecione</option>
                    <?php if ($id_obj_old != 0): ?>
                        <option value="<?= $id_obj_old; ?>" selected><?= $id_obj_old . ' - ' . $obj_old_name; ?></option>
                    <?php endif; ?>
                </select>
            </div>
            <div class="col-md-12">
                <label for="idObservacao" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Observações</label>
                <textarea 
                    class="form-control formulario-padrao-input" 
                    id="idObservacao" 
                    name="observacao" 
                    rows="1"
                ><?= $movimento['observacao'] ?? ''; ?></textarea>
            </div>
        </div>
    </div>
</div>