<div class="modal-header p-2">
    <h5 class="modal-title" id="modal-conteudo-titulo"><?= $this->view->titulo; ?></h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body p-0">
    <div class="row g-4 p-3">
        <div class="col-12">
            <div class="card-body">
                <div class="border rounded p-3 bg-light">
                    <span><?= $observacao; ?></span>
                </div>
            </div>
        </div>
    </div>
</div>