<div class="container">
    <div class="mt-2 mb-2">
		<div class="card p-2">
			<div class="text-center">
				<?= $title; ?>
			</div>
		</div>
	</div>

    <div class="card border-0 shadow-sm formulario-padrao-card">
        <div class="card-header bg-dark text-white">
            <div class="d-flex align-items-center">
                <i class="bi bi-file-earmark-text fs-4 me-2"></i>
                <h6 class="card-title mb-0">Filtro</h6>
            </div>
        </div>
        <div class="card-body p-2">
            <form method="POST" data-action="<?= $action; ?>" class="submit-form-render-ajax" data-div="<?= $div; ?>">
                <div class="form-group">
                    <div class="row g-2">
                        <div class="col-sm-4 col-12">
                            <label for="mesAno" class="form-label titulo-input-formulario-cadastro formulario-padrao-label">Mês/Ano</label>
                            <input type="month" class="form-control formulario-padrao-input" id="mesAno" name="mes_ano" required>
                        </div>
                    </div>
                </div>

                <div class="mt-1">
                    <button id="salvar" type="submit" class="btn btn-primary m-1">Processar</button>
                </div>
            </form>
        </div>
    </div>

    <div id="<?= $div; ?>"></div>
</div>