<?php 
	$buttons = $this->view->buttons ?? false;
	$margin_bottom = '';
	if ($buttons) {
		$margin_bottom = 'margin-bottom: 50px;';
	}
?>

<html lang="pt-br">

	<?php require_once ('view_head.php'); ?>

	<body>
        <?php require ('menu.phtml'); ?>

		<main id="grid-principal">

			<div style="<?= $margin_bottom; ?>">
				<?php 
					if ($this->view->base_interna != '')
						$this->carregarBaseInterna();
					else
						$this->carregarConteudo();
				?>
			</div>

			<?php if ($buttons): ?>
                <div id="fixedBotton" class="bg-navbar-top-and-bottom">
                    <div class="container">
                        <?php foreach ($buttons as $btn): ?>
                            <button 
                                type="button"
                                title="<?= $btn['title']; ?>"
                                data-url="<?= $btn['action']; ?>"
                                class="<?= $btn['classes']; ?> <?= ($btn['position'] == 'right' ? 'float-end' : 'float-start') ?>"
                                data-modal="<?= $btn['modal']; ?>"
                            >
                                <?= $btn['title']; ?>
                            </button>
                        <?php endforeach; ?>
                        <div class="clearfix"></div>
                    </div>
                </div>
            <?php endif; ?>
		</main>

		<?php include ('modal_alerta.phtml') ?>
		<?php include ('modal.phtml') ?>

        <div class="loading-overlay" id="loadingOverlay">
            <div class="spinner"></div>
        </div>
	</body>

	<?php require_once ('view_bottom.php'); ?>

</html>