<?php 
	$buttons = $this->view->buttons ?? false;
?>

<html lang="pt-br">

	<?php require_once ('view_head.php'); ?>

    <?php 
        if ($_SERVER['REQUEST_URI'] != '/primeiro-acesso'): 
    ?>
        <body class="bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 p-3">
                        <div class="d-lg-flex justify-content-between align-items-center mb-3">
                            <a href="home" style="text-decoration: none;"> <h5 class="mb-0 fw-bold text-primary mb-lg-0 mb-3 text-center text-lg-start"><?= $this->empresa; ?></h5> </a>
                            <?php require ('form_pesquisa.phtml'); ?>
                        </div>
                    </div>
                </div>
            </div>

    <?php
            require ('menu.phtml');
        endif;
    ?>

		<main id="grid-principal">
			<div>
				<?php 
					if ($this->view->base_interna != '')
						$this->carregarBaseInterna();
					else
						$this->carregarConteudo();
				?>
			</div>

			<?php if ($buttons): ?>
                <div id="fixedBottom" class="fixed-bottom bg-light border-top shadow-sm py-3">
                    <div class="container">
                        <div class="d-flex justify-content-between align-items-center">
                            <?php foreach ($buttons as $btn): ?>
                                <button
                                    type="button"
                                    title="<?= $btn['title']; ?>"
                                    data-url="<?= $btn['action']; ?>"
                                    class="<?= $btn['classes']; ?> <?= ($btn['position'] == 'right' ? 'float-end' : 'float-start') ?>"
                                    data-modal="<?= $btn['modal']; ?>"
                                >
                                    <?= $btn['title']; ?>
                                </button>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
		</main>

		<?php include ('modal_alerta.phtml') ?>
		<?php include ('modal.phtml') ?>

        <div class="loading-overlay" id="loadingOverlay">
            <div class="spinner"></div>
        </div>
	</body>

	<?php require_once ('view_bottom.php'); ?>

</html>