<div class="container">
	<div class="mt-2 mb-2">
		<div class="card p-2">
			<div class="text-center">
				<?= $title; ?>
			</div>
		</div>
	</div>

	<div class="mt-2 mb-2">
		<form 
			class="form-inline" 
			method="POST" 
			name="form-crud" 
			id="idform-crud" 
			data-action="<?= $action; ?>" 
			data-redirect="<?= $redirect; ?>"
		>
			<div>
				<?= $this->carregarConteudo(); ?>
			</div>

				<div class="mt-1 p-2 bg-light bg-gradient border border-2 rounded"> 
					<button id="salvar" type="button" class="btn btn-success m-1" onclick="submitFormCrud()">Salvar</button>
					<button id="cancelar" class="btn btn-danger m-1" type="button" onclick="returnToIndex()">Cancelar/Voltar</button>       
				</div>
			</div>
		</form>
	</div>
</div>