<div class="container">
	<div class="mt-2 mb-2">
		<div class="card p-2">
			<div class="text-center">
				<?= $title; ?>
			</div>
		</div>
	</div>

	<div class="mt-2 mb-2">
		<form
			class="form-inline submit-form-crud-ajax"
			method="POST"
			name="form-crud"
			id="idform-crud"
			data-action="<?= $action; ?>"
			data-redirect="<?= $redirect; ?>"
		>
			<div>
				<?= $this->carregarConteudo(); ?>
			</div>
            <div class="p-2 bg-light bg-gradient rounded"> 
                <button id="salvar" type="submit" class="btn btn-success m-1">Salvar</button>
                <button id="cancelar" class="btn btn-danger m-1" type="button" onclick="returnToHome()">Cancelar/Voltar</button>
            </div>
		</form>
	</div>

    <div>
        <?= $this->carregarConteudoExtra(); ?>
    </div>

    <?php if ($buttons): ?>
        <div id="fixedBottom" class="fixed-bottom bg-light border-top shadow-sm py-3">
            <div class="container">
                <div class="d-flex justify-content-between align-items-center">
                    <?php foreach ($buttons as $btn): ?>
                        <button
                            type="button"
                            title="<?= $btn['title']; ?>"
                            data-url="<?= $btn['action']; ?>"
                            class="<?= $btn['classes']; ?> <?= ($btn['position'] == 'right' ? 'float-end' : 'float-start') ?>"
                            data-modal="<?= $btn['modal']; ?>"
                        >
                            <?= $btn['title']; ?>
                        </button>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>