<?php $pesquisa = $_GET['pesquisa'] ?? ''; ?>

<form id="idFormPesquisa" class="form-ajax d-flex mb-0" action="<?= $this->view->settings['url_search']; ?>" method="GET" role="search">
    <?php require 'select_month.php'; ?>
    <input type="text" class="form-control me-2 ms-2" name="pesquisa" value="<?= $pesquisa; ?>">                        
    <button type="submit" class="btn btn-outline-primary send-ajax-render">Pesquisar</button>
</form>