<?php $pesquisa = $_GET['pesquisa'] ?? ''; ?>

<?php if (isset($this->view->settings['url_search'])): ?>
    <form id="idFormPesquisa" class="d-flex mb-0" action="<?= $this->view->settings['url_search']; ?>" method="GET" role="search">
        <?php require 'select_month.php'; ?>
        <input type="text" class="form-control me-2 ms-2" id="idPesquisa" name="pesquisa" value="<?= $pesquisa; ?>">                        
        <button type="submit" class="btn btn-outline-primary">Pesquisar</button>
        <button type="button" class="mx-2 btn btn-outline-danger limpar-pesquisa">X</button>
    </form>
<?php endif; ?>