<script>    
    <?php echo 'let ret = ' . $ret . ';'; ?>

    let mes_ano = Array();
    let arr_valores = Array();
    let arr_names = Array();
    let obj = Object();
    let final = Array();
    let proprietarios_nome = Object();

    let obj_2 = Object();
    let final_2 = Array();
    let arr_proprietario = Array();
    let arr_valores_2 = Array();

    for (const item of ret) {
        let index = mes_ano.indexOf(item.mesAno);
        let index2 = arr_valores.indexOf(item.idContaInvest);
        let index3 = arr_proprietario.indexOf(item.idProprietario);
        
        proprietarios_nome[item.idProprietario] = item.proprietarioNome

        if (index == -1) {
            mes_ano.push(item.mesAno);
        }

        if (index2 == -1) {
            arr_valores[item.idContaInvest] = Array();
            arr_names[item.idContaInvest] = item.nome;
        }

        if (index3 == -1) {
            arr_valores_2[`${item.idProprietario}-${item.mesAno}`] = 0;
        }
    }

    for (const item of ret) {
        arr_valores[item.idContaInvest].push(item.valor);
        arr_valores_2[`${item.idProprietario}-${item.mesAno}`] += item.valor;
    }

    arr_valores.forEach(function (v, id) {
        obj = {
            id: id,
            label: arr_names[id],
            data: v
        };

        final.push(obj);
    })

    for (const [key, value] of Object.entries(arr_valores_2)) {
        let spliting = key.split('-')[0];

        obj_2 = {
            label: spliting,
            data: value
        };

        final_2.push(obj_2);
    }

    let gerarDataPorProprietario = Array();

    final_2.forEach(function(v, i) {
        gerarDataPorProprietario[v.label] = Array();
    })

    final_2.forEach(function(v, i) {
        gerarDataPorProprietario[v.label].push(v.data);
    })

    final_2 = Array();

    for (const [key, value] of Object.entries(gerarDataPorProprietario)) {
        obj_2 = {
            label: key + ' - ' + proprietarios_nome[key],
            data: value
        };

        final_2.push(obj_2);
    }
</script>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div class="container">
    <canvas id="porContaInvestimento"></canvas>
    <canvas id="porProprietario"></canvas>
</div>

<script>
    let porContaInvestimento = document.getElementById('porContaInvestimento');
    let data_porContaInvestimento = {
        labels: mes_ano,
        datasets: final
    };

    let porProprietario = document.getElementById('porProprietario');
    let data_porProprietario = {
        labels: mes_ano,
        datasets: final_2
    };

    new Chart(porContaInvestimento, {
        type: 'line',
        data: data_porContaInvestimento,
        options: {
            responsive: true,
            plugins: {
            legend: {
                position: 'top',
            },
            title: {
                display: true,
                text: 'Chart.js Line Chart'
            }
            }
        },
        options: {
        scales: {
            y: {
                beginAtZero: false
            }
        }
    }
  });

  new Chart(porProprietario, {
        type: 'line',
        data: data_porProprietario,
        options: {
            responsive: true,
            plugins: {
            legend: {
                position: 'top',
            },
            title: {
                display: true,
                text: 'Chart.js Line Chart'
            }
            }
        },
        options: {
        scales: {
            y: {
            beginAtZero: false
            }
        }
    }
  });
</script>